import { useEffect, useState } from 'react';
import { useAuth } from '../contexts/AuthContext';
import { PageLayout } from '../components/layout/PageLayout';
import { Card } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { Badge } from '../components/ui/badge';
import { Progress } from '../components/ui/progress';
import { Skeleton } from '../components/ui/skeleton';
import { Separator } from '../components/ui/separator';
import axios from 'axios';
import { format, parseISO, subDays } from 'date-fns';
import { 
  Share2, 
  Download, 
  Copy,
  TrendingUp,
  CheckCircle2,
  XCircle,
  Clock,
  Calendar,
  Award,
  Pill
} from 'lucide-react';
import { toast } from 'sonner';

const API_URL = `${process.env.REACT_APP_BACKEND_URL}/api`;

const ShareProgressPage = () => {
  const { user } = useAuth();
  const [progress, setProgress] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchProgress = async () => {
      try {
        const response = await axios.get(`${API_URL}/progress/weekly`);
        setProgress(response.data);
      } catch (error) {
        console.error('Failed to fetch progress:', error);
        toast.error('Failed to load progress data');
      } finally {
        setLoading(false);
      }
    };

    fetchProgress();
  }, []);

  const generateShareText = () => {
    if (!progress) return '';
    
    const { summary, period } = progress;
    return `📊 My Weekly Medication Report (${progress.user_name})
    
📅 Period: ${format(parseISO(period.start), 'MMM d')} - ${format(parseISO(period.end), 'MMM d, yyyy')}

✅ Doses Taken: ${summary.taken}/${summary.total_doses}
📈 Adherence Rate: ${summary.adherence_rate}%
🔥 Current Streak: ${summary.current_streak} days

💊 Medications: ${progress.medications.map(m => m.name).join(', ')}

Generated by Vitality Medication Reminder`;
  };

  const handleShare = async () => {
    const text = generateShareText();
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'My Weekly Medication Progress',
          text: text,
        });
        toast.success('Shared successfully!');
      } catch (error) {
        if (error.name !== 'AbortError') {
          // Fallback to copy
          handleCopy();
        }
      }
    } else {
      handleCopy();
    }
  };

  const handleCopy = () => {
    const text = generateShareText();
    navigator.clipboard.writeText(text);
    toast.success('Copied to clipboard!');
  };

  const handleDownload = () => {
    const text = generateShareText();
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `medication-progress-${format(new Date(), 'yyyy-MM-dd')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success('Downloaded progress report!');
  };

  if (loading) {
    return (
      <PageLayout>
        <div className="space-y-6">
          <Skeleton className="h-12 w-48" />
          <Skeleton className="h-64" />
          <Skeleton className="h-48" />
        </div>
      </PageLayout>
    );
  }

  if (!progress) {
    return (
      <PageLayout>
        <Card className="p-12 text-center">
          <TrendingUp className="w-16 h-16 mx-auto text-muted-foreground/50 mb-4" />
          <h3 className="text-xl font-semibold mb-2">No Progress Data</h3>
          <p className="text-muted-foreground">
            Start logging your medications to see your progress here.
          </p>
        </Card>
      </PageLayout>
    );
  }

  const { summary, daily_breakdown, medications, period } = progress;

  // Get adherence color
  const getAdherenceColor = (rate) => {
    if (rate >= 90) return 'text-emerald-600';
    if (rate >= 70) return 'text-amber-600';
    return 'text-red-600';
  };

  // Sort daily breakdown by date descending
  const sortedDays = Object.entries(daily_breakdown)
    .sort(([a], [b]) => new Date(b) - new Date(a));

  return (
    <PageLayout>
      <div className="space-y-8 page-enter">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <div>
            <h1 className="text-3xl sm:text-4xl font-extrabold text-foreground">
              Weekly Progress
            </h1>
            <p className="text-lg text-muted-foreground mt-1">
              <Calendar className="w-4 h-4 inline mr-2" />
              {format(parseISO(period.start), 'MMM d')} - {format(parseISO(period.end), 'MMM d, yyyy')}
            </p>
          </div>
          <div className="flex gap-3">
            <Button 
              variant="outline" 
              size="lg"
              onClick={handleCopy}
              className="h-12"
              data-testid="copy-progress-btn"
            >
              <Copy className="w-5 h-5 mr-2" />
              Copy
            </Button>
            <Button 
              variant="outline" 
              size="lg"
              onClick={handleDownload}
              className="h-12"
              data-testid="download-progress-btn"
            >
              <Download className="w-5 h-5 mr-2" />
              Download
            </Button>
            <Button 
              size="lg"
              onClick={handleShare}
              className="h-12"
              data-testid="share-progress-btn"
            >
              <Share2 className="w-5 h-5 mr-2" />
              Share
            </Button>
          </div>
        </div>

        {/* Summary Cards */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <Card className="p-5 bg-white">
            <div className="flex items-center gap-3">
              <div className={`w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center`}>
                <TrendingUp className={`w-6 h-6 ${getAdherenceColor(summary.adherence_rate)}`} />
              </div>
              <div>
                <p className={`text-2xl font-bold ${getAdherenceColor(summary.adherence_rate)}`}>
                  {summary.adherence_rate}%
                </p>
                <p className="text-sm text-muted-foreground">Adherence</p>
              </div>
            </div>
          </Card>

          <Card className="p-5 bg-white">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-xl bg-emerald-100 flex items-center justify-center">
                <CheckCircle2 className="w-6 h-6 text-emerald-600" />
              </div>
              <div>
                <p className="text-2xl font-bold text-emerald-600">{summary.taken}</p>
                <p className="text-sm text-muted-foreground">Taken</p>
              </div>
            </div>
          </Card>

          <Card className="p-5 bg-white">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-xl bg-red-100 flex items-center justify-center">
                <XCircle className="w-6 h-6 text-red-600" />
              </div>
              <div>
                <p className="text-2xl font-bold text-red-600">{summary.missed}</p>
                <p className="text-sm text-muted-foreground">Missed</p>
              </div>
            </div>
          </Card>

          <Card className="p-5 bg-white">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center">
                <Award className="w-6 h-6 text-amber-600" />
              </div>
              <div>
                <p className="text-2xl font-bold text-amber-600">{summary.current_streak}</p>
                <p className="text-sm text-muted-foreground">Day Streak</p>
              </div>
            </div>
          </Card>
        </div>

        {/* Overall Progress Bar */}
        <Card className="p-6 bg-white">
          <h3 className="font-bold text-lg mb-4">Weekly Overview</h3>
          <div className="space-y-2">
            <div className="flex justify-between text-sm">
              <span>Total Progress</span>
              <span className="font-semibold">{summary.taken} / {summary.total_doses} doses</span>
            </div>
            <Progress value={summary.adherence_rate} className="h-4" />
          </div>
        </Card>

        {/* Daily Breakdown */}
        <Card className="p-6 bg-white">
          <h3 className="font-bold text-lg mb-4">Daily Breakdown</h3>
          <div className="space-y-4">
            {sortedDays.map(([date, stats]) => (
              <div key={date} className="flex items-center gap-4">
                <div className="w-24 text-sm font-medium text-muted-foreground">
                  {format(parseISO(date), 'EEE, MMM d')}
                </div>
                <div className="flex-1">
                  <Progress value={stats.adherence_rate} className="h-3" />
                </div>
                <div className="w-20 flex items-center justify-end gap-2">
                  <Badge 
                    variant="outline" 
                    className={`text-xs ${
                      stats.adherence_rate >= 90 ? 'bg-emerald-100 text-emerald-700' :
                      stats.adherence_rate >= 70 ? 'bg-amber-100 text-amber-700' :
                      'bg-red-100 text-red-700'
                    }`}
                  >
                    {stats.adherence_rate}%
                  </Badge>
                </div>
                <div className="w-16 text-right text-sm text-muted-foreground">
                  {stats.taken}/{stats.total}
                </div>
              </div>
            ))}
          </div>
        </Card>

        {/* Medications */}
        <Card className="p-6 bg-white">
          <h3 className="font-bold text-lg mb-4 flex items-center gap-2">
            <Pill className="w-5 h-5 text-primary" />
            Tracked Medications
          </h3>
          <div className="flex flex-wrap gap-2">
            {medications.map((med, index) => (
              <Badge key={index} variant="outline" className="text-sm py-1.5 px-3">
                {med.name} - {med.dosage}
              </Badge>
            ))}
          </div>
        </Card>

        {/* Disclaimer */}
        <Card className="p-4 bg-muted/30 border-muted">
          <p className="text-xs text-muted-foreground text-center">
            This progress report is for informational purposes only. 
            Share with your healthcare provider for medical discussions.
          </p>
        </Card>
      </div>
    </PageLayout>
  );
};

export default ShareProgressPage;
